project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "The relationship between health conditions and alcohol consumption"
  author:
    - YUNYAN OUYANG (yo2384)
    - BOSI HOU (bh2955)
  repo-url: https://github.com/yyouyang12/AlcoholConsumption.git
  date: today
  page-footer:
    right: |
      This book was built with <a href=" ">Quarto</a >.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd


format:
  html:
    theme: Journal
    code-fold: true

